# Generated by Django 5.1.7 on 2025-04-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitioWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('estado', models.CharField(default='Desconocido', max_length=20)),
                ('tiempo_respuesta', models.FloatField(blank=True, null=True)),
                ('ultimo_chequeo', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
